# SPDX-License-Identifier: Apache-2.0
name: Security Scan
permissions:
  contents: read

on:
  push:
    branches: [ main, dev ]
  pull_request:

jobs:
  secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Scan for secrets
        uses: trufflesecurity/trufflehog@v3.57.0
        with:
          args: "--path ."
